package types

type Location struct {
	Name       string
	URLPartial string
}

var Cities = []Location{
	{Name: "ablesserdam", URLPartial: "4-ablesserdam"},
	{Name: "alkmaar", URLPartial: "5-alkmaar"},
	{Name: "almelo", URLPartial: "6-almelo"},
	{Name: "almere", URLPartial: "7-almere"},
	{Name: "almkerk", URLPartial: "9-almkerk"},
	{Name: "alphen aan den rijn", URLPartial: "10-alphen-aan-den-rijn"},
	{Name: "amersfoort", URLPartial: "11-amersfoort"},
	{Name: "amstelveen", URLPartial: "12-amstelveen"},
	{Name: "amsterdam", URLPartial: "13-amsterdam"},
	{Name: "apeldoorn", URLPartial: "14-apeldoorn"},
	{Name: "arnhem", URLPartial: "15-arnhem"},
	{Name: "best", URLPartial: "25-best"},
	{Name: "breda", URLPartial: "32-breda"},
	{Name: "bussum", URLPartial: "34-bussum"},
	{Name: "castricum", URLPartial: "36-castricum"},
	{Name: "cuijk", URLPartial: "37-cuijk"},
	{Name: "delft", URLPartial: "40-delft"},
	{Name: "den bosch", URLPartial: "42-den-bosch"},
	{Name: "den haag", URLPartial: "44-den-haag"},
	{Name: "den helder", URLPartial: "45-den-helder"},
	{Name: "deventer", URLPartial: "47-deventer"},
	{Name: "diemen", URLPartial: "49-diemen"},
	{Name: "doetinchem", URLPartial: "52-doetinchem"},
	{Name: "dordrecht", URLPartial: "55-dordrecht"},
	{Name: "drachten", URLPartial: "57-drachten"},
	{Name: "ede", URLPartial: "63-ede"},
	{Name: "eindhoven", URLPartial: "64-eindhoven"},
	{Name: "emmeloord", URLPartial: "65-emmeloord"},
	{Name: "emmen", URLPartial: "66-emmen"},
	{Name: "enkhuizen", URLPartial: "67-enkhuizen"},
	{Name: "enschede", URLPartial: "68-enschede"},
	{Name: "goes", URLPartial: "75-goes"},
	{Name: "gorinchem", URLPartial: "77-gorinchem"},
	{Name: "groningen", URLPartial: "80-groningen"},
	{Name: "haarlem", URLPartial: "82-haarlem"},
	{Name: "hardenberg", URLPartial: "83-hardenberg"},
	{Name: "heerhugowaard", URLPartial: "89-heerhugowaard"},
	{Name: "hellevoetsluit", URLPartial: "92-hellevoetsluit"},
	{Name: "helmond", URLPartial: "93-helmond"},
	{Name: "hengelo ov", URLPartial: "94-hengelo-ov"},
	{Name: "hilversum", URLPartial: "96-hilversum"},
	{Name: "hoofddorp", URLPartial: "98-hoofddorp"},
	{Name: "hoogeveen", URLPartial: "99-hoogeveen"},
	{Name: "hoogezand", URLPartial: "100-hoogezand"},
	{Name: "hoorn", URLPartial: "101-hoorn"},
	{Name: "houten", URLPartial: "102-houten"},
	{Name: "huizen", URLPartial: "103-huizen"},
	{Name: "ijmuiden", URLPartial: "105-ijmuiden"},
	{Name: "kampen", URLPartial: "108-kampen"},
	{Name: "kerkrade", URLPartial: "110-kerkrade"},
	{Name: "klazienaveen", URLPartial: "111-klazienaveen"},
	{Name: "leeuwarden", URLPartial: "117-leeuwarden"},
	{Name: "leiden", URLPartial: "118-leiden"},
	{Name: "lisse", URLPartial: "122-lisse"},
	{Name: "maastricht", URLPartial: "124-maastricht"},
	{Name: "middelburg", URLPartial: "128-middelburg"},
	{Name: "nijmegen", URLPartial: "136-nijmegen"},
	{Name: "oss", URLPartial: "149-oss"},
	{Name: "panningen", URLPartial: "151-panningen"},
	{Name: "purmerend", URLPartial: "152-purmerend"},
	{Name: "reuver", URLPartial: "154-reuver"},
	{Name: "rotterdam", URLPartial: "159-rotterdam"},
	{Name: "schagen", URLPartial: "160-schagen"},
	{Name: "schiedam", URLPartial: "161-schiedam"},
	{Name: "sneek", URLPartial: "168-sneek"},
	{Name: "spijkenisse", URLPartial: "170-spijkenisse"},
	{Name: "stadskanaal", URLPartial: "171-stadskanaal"},
	{Name: "tilburg", URLPartial: "176-tilburg"},
	{Name: "utrecht", URLPartial: "178-utrecht"},
	{Name: "veghel", URLPartial: "182-veghel"},
	{Name: "venlo", URLPartial: "185-venlo"},
	{Name: "venray", URLPartial: "186-venray"},
	{Name: "vlaardingen", URLPartial: "187-vlaardingen"},
	{Name: "voorschoten", URLPartial: "190-voorschoten"},
	{Name: "wageningen", URLPartial: "192-wageningen"},
	{Name: "weert", URLPartial: "194-weert"},
	{Name: "woerden", URLPartial: "203-woerden"},
	{Name: "zaandam", URLPartial: "205-zaandam"},
	{Name: "zevenaar", URLPartial: "210-zevenaar"},
	{Name: "zierikzee", URLPartial: "211-zierikzee"},
	{Name: "zoetermeer", URLPartial: "212-zoetermeer"},
	{Name: "zutphen", URLPartial: "213-zutphen"},
	{Name: "zwolle", URLPartial: "214-zwolle"},
	{Name: "leischendam", URLPartial: "389-leischendam"},
	{Name: "utrecht", URLPartial: "178-utrecht"},
	{Name: "leiden", URLPartial: "118-leiden"},
}

// var CityURL = []string{
// 	"4-ablesserdam",
// 	"5-alkmaar",
// 	"6-almelo",
// 	"7-almere",
// 	"9-almkerk",
// 	"10-alphen-aan-den-rijn",
// 	"11-amersfoort",
// 	"12-amestelveen",
// 	"13-amsterdam",
// 	"14-apeldoorn",
// 	"15-arnhem",
// 	"25-best",
// 	"32-breda",
// 	"34-bussum",
// 	"36-castricum",
// 	"37-cuijk",
// 	"40-delft",
// 	"42-den-bosch",
// 	"44-den-haag",
// 	"45-den-helder",
// 	"47-deventer",
// 	"49-diemen",
// 	"52-doetinchem",
// 	"55-dordrecht",
// 	"57-drachten",
// 	"63-ede",
// 	"64-eindhoven",
// 	"65-emmeloord",
// 	"66-emmen",
// 	"67-enkhuizen",
// 	"68-enschede",
// 	"75-goes",
// 	"77-gorinchem",
// 	"80-groningen",
// 	"82-haarlem",
// 	"83-hardenberg",
// 	"89-heerhugowaard",
// 	"92-hellevoetsluit",
// 	"93-helmond",
// 	"94-hengelo-ov",
// 	"96-hilversum",
// 	"98-hoofddorp",
// 	"99-hoogeveen",
// 	"100-hoogezand",
// 	"101-hoorn",
// 	"102-houten",
// 	"103-huizen",
// 	"105-ijmuiden",
// 	"108-kampen",
// 	"110-kerkrade",
// 	"111-klazienaveen",
// 	"117-leeuwarden",
// 	"118-leiden",
// 	"122-lisse",
// 	"124-maastricht",
// 	"128-middelburg",
// 	"136-nijmegen",
// 	"149-oss",
// 	"151-panningen",
// 	"152-purmerend",
// 	"154-reuver",
// 	"159-rotterdam",
// 	"160-schagen",
// 	"161-schiedam",
// 	"168-sneek",
// 	"170-spijkenisse",
// 	"171-stadskanaal",
// 	"176-tilburg",
// 	"178-utrecht",
// 	"182-veghel",
// 	"185-venlo",
// 	"186-venray",
// 	"187-vlaardingen",
// 	"190-voorschoten",
// 	"192-wageningen",
// 	"194-weert",
// 	"203-woerden",
// 	"205-zaandam",
// 	"210-zevenaar",
// 	"211-zierikzee",
// 	"212-zoetermeer",
// 	"213-zutphen",
// 	"214-zwolle",
// 	"389-leischendam",
// 	"178-utrecht",
// 	"118-leiden",
// }
