services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: app
    ports:
      - 5432:5432
    hostname: postgres
    expose:
      - 5432
