// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUserWatchlist(ctx context.Context, userID int64) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetMatchingFilmEventsByEmail(ctx context.Context, email string) ([]GetMatchingFilmEventsByEmailRow, error)
	GetOrCreateUserID(ctx context.Context, email string) (int64, error)
	InsertFilmEvent(ctx context.Context, arg InsertFilmEventParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertWatchlistItem(ctx context.Context, arg InsertWatchlistItemParams) error
}

var _ Querier = (*Queries)(nil)
