// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUserWatchlist(ctx context.Context, email string) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetMatchingFilmEventsByEmail(ctx context.Context, email string) ([]GetMatchingFilmEventsByEmailRow, error)
	GetUserIDByEmail(ctx context.Context, email string) (int64, error)
	GetUserIDByToken(ctx context.Context, token string) (int64, error)
	GetUserWatchlist(ctx context.Context, email string) ([]string, error)
	InsertFilmEvent(ctx context.Context, arg InsertFilmEventParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	UpdateUserEmailConfirmation(ctx context.Context, arg UpdateUserEmailConfirmationParams) error
	UpdateUserWatchlist(ctx context.Context, arg UpdateUserWatchlistParams) error
}

var _ Querier = (*Queries)(nil)
