// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type FilmEvent struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Url             string    `json:"url"`
	StartDate       time.Time `json:"start_date"`
	EndDate         time.Time `json:"end_date"`
	LocationName    string    `json:"location_name"`
	LocationAddress string    `json:"location_address"`
	City            string    `json:"city"`
	OrganizerName   string    `json:"organizer_name"`
	OrganizerUrl    string    `json:"organizer_url"`
	PerformerName   string    `json:"performer_name"`
}

type User struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	LetterboxdUsername string     `json:"letterboxd_username"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
	Watchlist          []string   `json:"watchlist"`
}
