// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateFilmEvent(ctx context.Context, arg CreateFilmEventParams) (FilmEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFilmEvent(ctx context.Context, id int64) error
	DeletePastFilmEvents(ctx context.Context) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserWatchlist(ctx context.Context, email string) error
	GetFilmEventByID(ctx context.Context, id int64) (FilmEvent, error)
	GetFilmEventsByUserEmail(ctx context.Context, email string) ([]FilmEvent, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserWatchlist(ctx context.Context, email string) ([]string, error)
	GetUsers(ctx context.Context) ([]User, error)
	ListFilmEvents(ctx context.Context) ([]FilmEvent, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserWatchlist(ctx context.Context, arg UpdateUserWatchlistParams) error
}

var _ Querier = (*Queries)(nil)
