// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: watchlist.sql

package db

import (
	"context"
)

const deleteUserWatchlist = `-- name: DeleteUserWatchlist :exec
UPDATE users 
SET watchlist = NULL
WHERE email = $1
`

func (q *Queries) DeleteUserWatchlist(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserWatchlist, email)
	return err
}

const getUserWatchlist = `-- name: GetUserWatchlist :one
SELECT watchlist 
FROM users 
WHERE email = $1
`

func (q *Queries) GetUserWatchlist(ctx context.Context, email string) ([]string, error) {
	row := q.db.QueryRow(ctx, getUserWatchlist, email)
	var watchlist []string
	err := row.Scan(&watchlist)
	return watchlist, err
}

const updateUserWatchlist = `-- name: UpdateUserWatchlist :exec
UPDATE users 
SET watchlist = $2 
WHERE email = $1
`

type UpdateUserWatchlistParams struct {
	Email     string   `json:"email"`
	Watchlist []string `json:"watchlist"`
}

func (q *Queries) UpdateUserWatchlist(ctx context.Context, arg UpdateUserWatchlistParams) error {
	_, err := q.db.Exec(ctx, updateUserWatchlist, arg.Email, arg.Watchlist)
	return err
}
